spring.application.name=backend
server.port = 4210
# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=604800000

llm.api.key=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
ai.url=http://127.0.0.1:8000

spring.datasource.url=jdbc:mysql://localhost:3306/devika?useSSL=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

